export interface MSA{     
        accType:string,
        alternateMobile:string,
        attr1:string,
        attr2: string,
        attr3: string,
        attr4: any,
        baseLocation:string,
        addr1: string,
        addr2: string,
        addr3: string,
              latitude: any,
              longitude: any,
              pincodeId: any
            addrBookId: any,
            address:string,
            city:string,
            email:string,
            gstinNum:string,
            lkpConsigntypeId: string,
            mob:string,
            msaCustId: any,
            name: string,
            panNum: string,
            pincode: string,
            tanNum: string
        custName: string,
        descr: string,
        groupCode: string,
        id: any,
        mnthPotential: any,
        mobile: string,
        oldMsaCustId: any,
        opprId: any,
        opprName: string,
        originatingSrc: string,
        pan: string,
        phone: string,
        segment: string,
        sfdcAccId: string,
        sfdcMnthPotential3pl: any,
        sfdcMnthPotentialAir: any,
        sfdcMnthPotentialSurface: any,
        sfdcOpprId: string,
        sla: any,
        status: any,
        lookupVal:string,
}